//! `kb install-claude` / `kb uninstall-claude` — wire kickbacks-kit into
//! Claude Code: two global slash commands (/kbtop, /kbstatus) and the
//! statusLine setting.
//!
//! The installer never clobbers silently. The kickbacks extension usually owns
//! the statusLine already (it prints the current ad); `kb statusline` keeps
//! that ad and appends kb stats, so replacing the stock script is a wrap, not
//! a removal. Whatever was there before is backed up and `kb uninstall-claude`
//! restores it byte for byte.

use anyhow::{bail, Context, Result};
use crossterm::style::Stylize;
use serde_json::{json, Value};
use std::fs;
use std::io::Write as _;
use std::path::{Path, PathBuf};

use crate::paths;

/// Marker embedded in every file we create, so uninstall only ever deletes
/// files we own.
const MARKER: &str = "generated by kickbacks-kit";

const KBTOP_MD: &str = r#"---
description: Show the kickbacks-kit dashboard (one-shot snapshot)
allowed-tools: Bash(kb snapshot:*)
---
<!-- generated by kickbacks-kit; `kb uninstall-claude` removes this file -->

## Dashboard

!`kb snapshot --plain`

## Your task

Show the dashboard above to the user exactly as rendered, inside a fenced code block. Add at most one short sentence if something needs attention (killswitch active, signed out, unwatched hours). Do not re-draw or restyle the dashboard.
"#;

const KBSTATUS_MD: &str = r#"---
description: Are Kickback.ai ads flowing right now, and why
allowed-tools: Bash(kb status:*)
---
<!-- generated by kickbacks-kit; `kb uninstall-claude` removes this file -->

## Status

!`kb status`

## Your task

Relay the status output above to the user in a fenced code block, then one sentence on whether ads are flowing and, if not, why. If the killswitch is active, note it is server-side at Kickback.ai and not the user's doing.
"#;

/// What currently occupies the Claude Code statusLine.
#[derive(Debug, PartialEq, Eq)]
enum Existing {
    /// Already `kb statusline`.
    Ours,
    /// The stock kickbacks ad script (`vibe-ads-statusline.mjs`).
    Stock,
    /// Some unrelated user command.
    Other,
    /// No statusLine configured.
    None,
}

fn classify(settings: &Value) -> Existing {
    let cmd = settings
        .get("statusLine")
        .and_then(|s| s.get("command"))
        .and_then(|c| c.as_str());
    match cmd {
        None => Existing::None,
        Some(c)
            if c.contains("kb statusline")
                || (c.contains("kb.exe") && c.contains("statusline")) =>
        {
            Existing::Ours
        }
        Some(c) if c.contains("vibe-ads-statusline") => Existing::Stock,
        Some(_) => Existing::Other,
    }
}

/// Return `settings` with the statusLine pointing at `exe statusline`.
/// Everything else in the document is preserved.
fn with_our_statusline(mut settings: Value, exe: &str) -> Value {
    if !settings.is_object() {
        settings = json!({});
    }
    settings["statusLine"] = json!({
        "type": "command",
        "command": format!("\"{exe}\" statusline"),
        "padding": 0,
    });
    settings
}

/// Return `settings` with our statusLine removed: restored from `backup` when
/// one exists, dropped otherwise.
fn without_our_statusline(mut settings: Value, backup: Option<Value>) -> Value {
    match backup {
        Some(original) => settings["statusLine"] = original,
        None => {
            if let Some(obj) = settings.as_object_mut() {
                obj.remove("statusLine");
            }
        }
    }
    settings
}

fn claude_dir() -> Result<PathBuf> {
    if let Ok(p) = std::env::var("CLAUDE_CONFIG_DIR") {
        return Ok(PathBuf::from(p));
    }
    let home = dirs::home_dir().context("could not resolve home directory")?;
    Ok(home.join(".claude"))
}

fn backup_path() -> Result<PathBuf> {
    Ok(paths::data_dir()?.join("claude-statusline-backup.json"))
}

fn read_settings(path: &Path) -> Result<Value> {
    if !path.exists() {
        return Ok(json!({}));
    }
    let raw = fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
    if raw.trim().is_empty() {
        return Ok(json!({}));
    }
    serde_json::from_str(&raw).with_context(|| {
        format!(
            "{} is not valid JSON; fix it before kb edits it",
            path.display()
        )
    })
}

fn confirm(question: &str, assume_yes: bool) -> Result<bool> {
    if assume_yes {
        return Ok(true);
    }
    print!("{question} [y/N] ");
    std::io::stdout().flush()?;
    let mut line = String::new();
    std::io::stdin().read_line(&mut line)?;
    Ok(matches!(line.trim(), "y" | "Y" | "yes" | "Yes"))
}

fn write_command_file(dir: &Path, name: &str, content: &str, assume_yes: bool) -> Result<bool> {
    let path = dir.join(name);
    if path.exists() {
        let existing = fs::read_to_string(&path).unwrap_or_default();
        if !existing.contains(MARKER)
            && !confirm(
                &format!(
                    "{} exists and was not created by kb. Overwrite?",
                    path.display()
                ),
                assume_yes,
            )?
        {
            println!("  {} kept existing {}", "•".yellow(), path.display());
            return Ok(false);
        }
    }
    fs::write(&path, content).with_context(|| format!("writing {}", path.display()))?;
    println!("  {} {}", "✓".green(), path.display());
    Ok(true)
}

pub fn install(assume_yes: bool) -> Result<()> {
    println!("{}", "kickbacks-kit · install-claude".bold());
    println!();

    let claude = claude_dir()?;
    if !claude.exists() {
        bail!("{} not found. Is Claude Code installed?", claude.display());
    }

    // 1. Global slash commands.
    let commands = claude.join("commands");
    fs::create_dir_all(&commands).with_context(|| format!("creating {}", commands.display()))?;
    write_command_file(&commands, "kbtop.md", KBTOP_MD, assume_yes)?;
    write_command_file(&commands, "kbstatus.md", KBSTATUS_MD, assume_yes)?;

    // 2. statusLine.
    let settings_path = claude.join("settings.json");
    let settings = read_settings(&settings_path)?;
    let exe = std::env::current_exe().context("resolving the kb executable path")?;
    let exe = exe.to_string_lossy().into_owned();

    match classify(&settings) {
        Existing::Ours => {
            // Re-point in case the binary moved; it is ours either way.
            let updated = with_our_statusline(settings, &exe);
            fs::write(&settings_path, serde_json::to_string_pretty(&updated)?)?;
            println!(
                "  {} statusLine already kb statusline (path refreshed)",
                "✓".green()
            );
        }
        Existing::None => {
            let updated = with_our_statusline(settings, &exe);
            fs::write(&settings_path, serde_json::to_string_pretty(&updated)?)?;
            println!("  {} statusLine set to kb statusline", "✓".green());
        }
        kind @ (Existing::Stock | Existing::Other) => {
            let old = settings["statusLine"].clone();
            let question = match kind {
                Existing::Stock => {
                    "Claude Code currently shows the Kickback.ai ad line. Wrap it with kb statusline (same ad, plus your kb stats)?"
                }
                _ => "Claude Code has a custom statusLine. Replace it with kb statusline (a backup will be kept)?",
            };
            if !confirm(question, assume_yes)? {
                println!("  {} statusLine left unchanged", "•".yellow());
                println!();
                println!("done. /kbtop and /kbstatus work in any Claude Code session.");
                return Ok(());
            }
            // First backup wins: it is the true original for uninstall.
            let backup = backup_path()?;
            if !backup.exists() {
                fs::write(&backup, serde_json::to_string_pretty(&old)?)
                    .with_context(|| format!("writing {}", backup.display()))?;
            }
            let updated = with_our_statusline(settings, &exe);
            fs::write(&settings_path, serde_json::to_string_pretty(&updated)?)?;
            println!("  {} statusLine set to kb statusline", "✓".green());
            println!(
                "  {} previous statusLine backed up to {}",
                "•".cyan(),
                backup.display()
            );
        }
    }

    println!();
    println!("done. restart Claude Code (or open a new session), then:");
    println!(
        "  {}     dashboard snapshot in the conversation",
        "/kbtop".bold()
    );
    println!("  {}  ad status and why", "/kbstatus".bold());
    println!("revert anytime with {}", "kb uninstall-claude".bold());
    Ok(())
}

pub fn uninstall(assume_yes: bool) -> Result<()> {
    println!("{}", "kickbacks-kit · uninstall-claude".bold());
    println!();

    let claude = claude_dir()?;
    let commands = claude.join("commands");
    for name in ["kbtop.md", "kbstatus.md"] {
        let path = commands.join(name);
        if path.exists() {
            let content = fs::read_to_string(&path).unwrap_or_default();
            if content.contains(MARKER) {
                fs::remove_file(&path).with_context(|| format!("removing {}", path.display()))?;
                println!("  {} removed {}", "✓".green(), path.display());
            } else {
                println!(
                    "  {} {} was not created by kb, kept",
                    "•".yellow(),
                    path.display()
                );
            }
        }
    }

    let settings_path = claude.join("settings.json");
    let settings = read_settings(&settings_path)?;
    if classify(&settings) == Existing::Ours {
        let backup_file = backup_path()?;
        let backup = if backup_file.exists() {
            let raw = fs::read_to_string(&backup_file)?;
            serde_json::from_str::<Value>(&raw).ok()
        } else {
            None
        };
        let restoring = backup.is_some();
        if confirm(
            if restoring {
                "Restore the previous statusLine?"
            } else {
                "Remove the kb statusLine (no backup found, the key will be dropped)?"
            },
            assume_yes,
        )? {
            let updated = without_our_statusline(settings, backup);
            fs::write(&settings_path, serde_json::to_string_pretty(&updated)?)?;
            if restoring {
                fs::remove_file(&backup_file).ok();
                println!("  {} statusLine restored from backup", "✓".green());
            } else {
                println!("  {} statusLine removed", "✓".green());
            }
        }
    } else {
        println!("  {} statusLine is not kb's, left unchanged", "•".yellow());
    }

    println!();
    println!("done.");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn settings_with_command(cmd: &str) -> Value {
        json!({
            "env": {"X": "1"},
            "statusLine": {"type": "command", "command": cmd, "padding": 0}
        })
    }

    #[test]
    fn classifies_every_statusline_owner() {
        assert_eq!(classify(&json!({})), Existing::None);
        assert_eq!(
            classify(&settings_with_command(
                "node \"C:\\\\Users\\\\x\\\\.vibe-ads\\\\vibe-ads-statusline.mjs\""
            )),
            Existing::Stock
        );
        assert_eq!(
            classify(&settings_with_command("kb statusline")),
            Existing::Ours
        );
        assert_eq!(
            classify(&settings_with_command(
                "\"C:\\\\Users\\\\x\\\\.cargo\\\\bin\\\\kb.exe\" statusline"
            )),
            Existing::Ours
        );
        assert_eq!(
            classify(&settings_with_command("my-own-script.sh")),
            Existing::Other
        );
    }

    #[test]
    fn install_preserves_other_settings() {
        let before = settings_with_command("whatever");
        let after = with_our_statusline(before, "C:\\bin\\kb.exe");
        assert_eq!(after["env"]["X"], "1");
        assert_eq!(
            after["statusLine"]["command"],
            "\"C:\\bin\\kb.exe\" statusline"
        );
        assert_eq!(after["statusLine"]["padding"], 0);
    }

    #[test]
    fn uninstall_restores_the_backup() {
        let ours = with_our_statusline(settings_with_command("old"), "kb.exe");
        let backup = json!({"type": "command", "command": "old", "padding": 0});
        let restored = without_our_statusline(ours, Some(backup));
        assert_eq!(restored["statusLine"]["command"], "old");
        assert_eq!(restored["env"]["X"], "1");
    }

    #[test]
    fn uninstall_without_backup_drops_the_key() {
        let ours = with_our_statusline(json!({"a": 1}), "kb.exe");
        let restored = without_our_statusline(ours, None);
        assert!(restored.get("statusLine").is_none());
        assert_eq!(restored["a"], 1);
    }

    #[test]
    fn command_files_carry_the_marker() {
        assert!(KBTOP_MD.contains(MARKER));
        assert!(KBSTATUS_MD.contains(MARKER));
    }
}
