use anyhow::{Context, Result};
use crossterm::style::Stylize;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::Command;

use crate::{integrations, paths};

const MARKER: &str = "generated by kickbacks-kit";
const PROBE_SAFE_INSTALL_NOTE: &str = "install, repair, doctor, skills, and generated plugin commands are non-earning probes; they never create fabricated, payable, billing, or payout events";
const OPT_IN_ADAPTER_NOTE: &str = "official opt-in earning adapters require user control, visible wait-state proof, backend attestation, caps, refund windows, and reconciliation";

#[derive(Debug, Clone, Default)]
pub struct InstallSelection {
    pub all: bool,
    pub vscode: bool,
    pub claude_cli: bool,
    pub codex_cli: bool,
    pub hermes: bool,
    pub skills: bool,
    pub yes: bool,
}

pub fn install(selection: InstallSelection) -> Result<()> {
    let targets = selection.resolve();
    println!("{}", "kickbacks-kit - plug-and-play installer".bold());
    println!();
    println!("  {} {}", "probe".cyan(), PROBE_SAFE_INSTALL_NOTE);
    println!("  {} {}", "adapter".cyan(), OPT_IN_ADAPTER_NOTE);
    println!();

    if targets.vscode {
        install_vscode_extension()?;
    }
    if targets.claude_cli {
        crate::install_claude::install(selection.yes)?;
        install_claude_commands()?;
    }
    if targets.skills {
        install_skills()?;
    }
    if targets.hermes {
        install_hermes_plugin()?;
    }
    if targets.codex_cli {
        println!(
            "  {} Codex CLI integration ready through `kickbacks codex` and the Codex skill",
            "*".cyan()
        );
    }

    println!();
    println!(
        "{}",
        "Installed surfaces are visible in `kickbacks app`.".green()
    );
    Ok(())
}

pub fn repair(selection: InstallSelection) -> Result<()> {
    println!("{}", "kickbacks-kit - repair".bold());
    install(selection)
}

pub fn restore() -> Result<()> {
    println!("{}", "kickbacks-kit - restore".bold());
    println!();

    let home = dirs::home_dir().context("could not resolve home directory")?;
    let mut report = RestoreReport::default();

    for dir in [
        home.join(".claude").join("skills").join("kickbacks"),
        home.join(".codex").join("skills").join("kickbacks"),
        home.join(".hermes").join("skills").join("kickbacks"),
    ] {
        restore_marker_file(&dir.join("SKILL.md"), &mut report)?;
        remove_empty_dir(&dir)?;
    }

    let claude_commands = home.join(".claude").join("commands");
    for name in [
        "kbtop.md",
        "kbstatus.md",
        "kickbacks.md",
        "kickbacks-status.md",
        "kickbacks-repair.md",
        "kickbacks-dashboard.md",
        "kickbacks-trust.md",
        "kickbacks-doctor.md",
    ] {
        restore_marker_file(&claude_commands.join(name), &mut report)?;
    }

    let hermes_commands = home.join(".hermes").join("commands");
    for name in [
        "kickbacks.md",
        "kickbacks-install.md",
        "kickbacks-status.md",
        "kickbacks-repair.md",
        "kickbacks-dashboard.md",
        "kickbacks-sync.md",
        "kickbacks-trust.md",
        "kickbacks-doctor.md",
    ] {
        restore_marker_file(&hermes_commands.join(name), &mut report)?;
    }

    let hermes_plugin = home.join(".hermes").join("plugins").join("kickbacks");
    for name in ["plugin.yaml", "__init__.py"] {
        restore_marker_file(&hermes_plugin.join(name), &mut report)?;
    }
    remove_empty_dir(&hermes_plugin)?;

    println!(
        "  {} restore summary: {} restored, {} removed, {} kept, {} missing",
        "ok".green(),
        report.restored,
        report.removed,
        report.kept,
        report.missing
    );
    println!(
        "  {} Use `kb uninstall-claude --yes` to restore Claude Code statusLine backup.",
        "*".yellow()
    );
    println!(
        "  {} Restore only removes marker-owned files, or restores their last recorded marker-owned backup byte-for-byte.",
        "*".yellow()
    );
    println!(
        "  {} Backup records live under the Kickback.ai data directory and never authorize payable events.",
        "*".yellow()
    );
    Ok(())
}

impl InstallSelection {
    fn resolve(&self) -> Targets {
        let default_all = !self.all
            && !self.vscode
            && !self.claude_cli
            && !self.codex_cli
            && !self.hermes
            && !self.skills;
        Targets {
            vscode: default_all || self.all || self.vscode,
            claude_cli: default_all || self.all || self.claude_cli,
            codex_cli: default_all || self.all || self.codex_cli,
            hermes: default_all || self.all || self.hermes,
            skills: default_all
                || self.all
                || self.skills
                || self.claude_cli
                || self.codex_cli
                || self.hermes,
        }
    }
}

struct Targets {
    vscode: bool,
    claude_cli: bool,
    codex_cli: bool,
    hermes: bool,
    skills: bool,
}

fn install_vscode_extension() -> Result<()> {
    match integrations::find_executable("code") {
        Some(code) => {
            let status = Command::new(&code)
                .args(["--install-extension", "Kickbacksai.kickbacks-ai", "--force"])
                .status()
                .with_context(|| format!("running {}", code.display()))?;
            if status.success() {
                println!(
                    "  {} VS Code extension install/update requested",
                    "ok".green()
                );
            } else {
                println!(
                    "  {} VS Code extension command exited with {status}",
                    "*".yellow()
                );
            }
        }
        None => {
            println!(
                "  {} VS Code `code` command not found; install extension from Marketplace",
                "*".yellow()
            );
        }
    }
    Ok(())
}

fn install_skills() -> Result<()> {
    let home = dirs::home_dir().context("could not resolve home directory")?;
    let targets = [
        (
            home.join(".claude").join("skills").join("kickbacks"),
            skill_md("Claude"),
        ),
        (
            home.join(".codex").join("skills").join("kickbacks"),
            skill_md("Codex"),
        ),
        (
            home.join(".hermes").join("skills").join("kickbacks"),
            skill_md("Hermes"),
        ),
    ];
    for (dir, content) in targets {
        write_marker_file(&dir.join("SKILL.md"), &content)?;
        println!("  {} {}", "ok".green(), dir.join("SKILL.md").display());
    }
    Ok(())
}

fn install_claude_commands() -> Result<()> {
    let home = dirs::home_dir().context("could not resolve home directory")?;
    let commands = home.join(".claude").join("commands");
    let items = [
        (
            "kickbacks.md",
            claude_command("Kickback.ai dashboard status", "kickbacks api health"),
        ),
        (
            "kickbacks-status.md",
            claude_command("Kickback.ai status", "kickbacks sync status"),
        ),
        (
            "kickbacks-repair.md",
            claude_command(
                "Kickback.ai repair",
                "kickbacks repair --claude-cli --skills --yes",
            ),
        ),
        (
            "kickbacks-dashboard.md",
            claude_command("Kickback.ai dashboard status", "kickbacks api health"),
        ),
        (
            "kickbacks-trust.md",
            claude_command("Kickback.ai Trust Engine", "kickbacks trust"),
        ),
        (
            "kickbacks-doctor.md",
            claude_command("Kickback.ai doctor", "kickbacks doctor"),
        ),
    ];
    for (name, content) in items {
        write_marker_file(&commands.join(name), &content)?;
    }
    println!("  {} Claude slash commands installed", "ok".green());
    Ok(())
}

fn install_hermes_plugin() -> Result<()> {
    let home = dirs::home_dir().context("could not resolve home directory")?;
    let dir = home.join(".hermes").join("plugins").join("kickbacks");
    write_marker_file(&dir.join("plugin.yaml"), HERMES_PLUGIN_YAML)?;
    write_marker_file(&dir.join("__init__.py"), HERMES_PLUGIN_PY)?;
    install_hermes_tui_commands(&home)?;
    println!(
        "  {} Hermes plugin installed at {}",
        "ok".green(),
        dir.display()
    );
    Ok(())
}

fn install_hermes_tui_commands(home: &Path) -> Result<()> {
    let commands = home.join(".hermes").join("commands");
    let items = [
        (
            "kickbacks.md",
            hermes_command("Kickback.ai trust status", "kickbacks trust"),
        ),
        (
            "kickbacks-status.md",
            hermes_command("Kickback.ai sync status", "kickbacks sync status"),
        ),
        (
            "kickbacks-install.md",
            hermes_command(
                "Kickback.ai install",
                "kickbacks install --hermes --skills --yes",
            ),
        ),
        (
            "kickbacks-repair.md",
            hermes_command(
                "Kickback.ai repair",
                "kickbacks repair --hermes --skills --yes",
            ),
        ),
        (
            "kickbacks-dashboard.md",
            hermes_command("Kickback.ai dashboard status", "kickbacks api health"),
        ),
        (
            "kickbacks-sync.md",
            hermes_command("Kickback.ai account sync", "kickbacks sync status"),
        ),
        (
            "kickbacks-trust.md",
            hermes_command("Kickback.ai Trust Engine", "kickbacks trust"),
        ),
        (
            "kickbacks-doctor.md",
            hermes_command("Kickback.ai doctor", "kickbacks doctor"),
        ),
    ];
    for (name, content) in items {
        write_marker_file(&commands.join(name), &content)?;
    }
    println!("  {} Hermes TUI command manifests installed", "ok".green());
    Ok(())
}

fn write_marker_file(path: &Path, content: &str) -> Result<()> {
    let backup_path = backup_record_path()?;
    write_marker_file_with_backup(path, content, &backup_path)
}

fn write_marker_file_with_backup(path: &Path, content: &str, backup_path: &Path) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).with_context(|| format!("creating {}", parent.display()))?;
    }
    let new_bytes = content.as_bytes();
    if path.exists() {
        let existing = fs::read(path).with_context(|| format!("reading {}", path.display()))?;
        if !String::from_utf8_lossy(&existing).contains(MARKER) {
            anyhow::bail!(
                "{} exists and was not created by kickbacks-kit; refusing to overwrite",
                path.display()
            );
        }
        if existing == new_bytes {
            return Ok(());
        }
        record_marker_backup(path, &existing, backup_path)?;
    }
    fs::write(path, new_bytes).with_context(|| format!("writing {}", path.display()))?;
    Ok(())
}

#[derive(Default)]
struct RestoreReport {
    restored: usize,
    removed: usize,
    kept: usize,
    missing: usize,
}

fn restore_marker_file(path: &Path, report: &mut RestoreReport) -> Result<()> {
    let backup_path = backup_record_path()?;
    restore_marker_file_with_backup(path, report, &backup_path)
}

fn restore_marker_file_with_backup(
    path: &Path,
    report: &mut RestoreReport,
    backup_path: &Path,
) -> Result<()> {
    if !path.exists() {
        report.missing += 1;
        return Ok(());
    }

    let existing = fs::read(path).with_context(|| format!("reading {}", path.display()))?;
    if String::from_utf8_lossy(&existing).contains(MARKER) {
        if let Some(record) = last_backup_for_path(backup_path, path)? {
            let bytes = hex_decode(&record.bytes_hex)?;
            anyhow::ensure!(
                sha256_hex(&bytes) == record.sha256,
                "backup checksum mismatch for {}",
                path.display()
            );
            fs::write(path, bytes).with_context(|| format!("restoring {}", path.display()))?;
            report.restored += 1;
            println!("  {} restored {}", "ok".green(), path.display());
        } else {
            fs::remove_file(path).with_context(|| format!("removing {}", path.display()))?;
            report.removed += 1;
            println!("  {} removed {}", "ok".green(), path.display());
        }
    } else {
        report.kept += 1;
        println!("  {} kept non-marker file {}", "*".yellow(), path.display());
    }
    Ok(())
}

#[derive(Debug, Clone, Deserialize, Serialize)]
struct BackupRecord {
    path: String,
    sha256: String,
    bytes_hex: String,
}

fn backup_record_path() -> Result<PathBuf> {
    Ok(paths::data_dir()?.join("install-backups.jsonl"))
}

fn record_marker_backup(path: &Path, bytes: &[u8], backup_path: &Path) -> Result<()> {
    if let Some(parent) = backup_path.parent() {
        fs::create_dir_all(parent).with_context(|| format!("creating {}", parent.display()))?;
    }
    let record = BackupRecord {
        path: path_key(path),
        sha256: sha256_hex(bytes),
        bytes_hex: hex_encode(bytes),
    };
    let mut file = fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(backup_path)
        .with_context(|| format!("opening {}", backup_path.display()))?;
    let line = serde_json::to_string(&record)?;
    writeln!(file, "{line}").with_context(|| format!("writing {}", backup_path.display()))?;
    Ok(())
}

fn last_backup_for_path(backup_path: &Path, path: &Path) -> Result<Option<BackupRecord>> {
    if !backup_path.exists() {
        return Ok(None);
    }
    let target = path_key(path);
    let raw = fs::read_to_string(backup_path)
        .with_context(|| format!("reading {}", backup_path.display()))?;
    let mut found = None;
    for line in raw.lines().filter(|line| !line.trim().is_empty()) {
        let record: BackupRecord = serde_json::from_str(line)
            .with_context(|| format!("parsing {}", backup_path.display()))?;
        if record.path == target {
            found = Some(record);
        }
    }
    Ok(found)
}

fn path_key(path: &Path) -> String {
    path.canonicalize()
        .unwrap_or_else(|_| path.to_path_buf())
        .display()
        .to_string()
}

fn sha256_hex(bytes: &[u8]) -> String {
    hex_encode(&Sha256::digest(bytes))
}

fn hex_encode(bytes: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut out = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        out.push(HEX[(byte >> 4) as usize] as char);
        out.push(HEX[(byte & 0x0f) as usize] as char);
    }
    out
}

fn hex_decode(raw: &str) -> Result<Vec<u8>> {
    anyhow::ensure!(raw.len() % 2 == 0, "invalid hex length");
    let bytes = raw.as_bytes();
    let mut out = Vec::with_capacity(raw.len() / 2);
    let mut i = 0;
    while i < bytes.len() {
        let high = hex_value(bytes[i])?;
        let low = hex_value(bytes[i + 1])?;
        out.push((high << 4) | low);
        i += 2;
    }
    Ok(out)
}

fn hex_value(byte: u8) -> Result<u8> {
    match byte {
        b'0'..=b'9' => Ok(byte - b'0'),
        b'a'..=b'f' => Ok(byte - b'a' + 10),
        b'A'..=b'F' => Ok(byte - b'A' + 10),
        _ => anyhow::bail!("invalid hex byte"),
    }
}

fn remove_empty_dir(path: &Path) -> Result<()> {
    if path.exists() {
        match fs::remove_dir(path) {
            Ok(()) => {}
            Err(err) if is_directory_not_empty(&err) => {}
            Err(err) if err.kind() == std::io::ErrorKind::NotFound => {}
            Err(err) => return Err(err).with_context(|| format!("removing {}", path.display())),
        }
    }
    Ok(())
}

fn is_directory_not_empty(err: &std::io::Error) -> bool {
    matches!(err.raw_os_error(), Some(145 | 39 | 17))
}

fn skill_md(surface: &str) -> String {
    format!(
        r#"---
name: kickbacks
description: "Kickback.ai desktop, CLI, ledger freshness, Stripe payout, and agent integration guidance. Use when working with Kickback.ai installs, earnings status, VS Code, Claude Code CLI, Codex CLI, Hermes Agent/TUI, Stripe payout readiness, or ledger diagnostics."
---

# Kickback.ai

<!-- {MARKER} -->

Use this skill when a user asks about Kickback.ai install state, earnings visibility,
ledger freshness, bot/fraud pressure, advertiser trust, Stripe payout readiness, or agent/CLI
setup from {surface}.

## Rules

- Official opt-in earning adapters can exist across CLI/TUI, desktop, Telegram,
  Discord, and other surfaces only when user-enabled, visible, backend-attested,
  capped, refund-windowed, and reconciled. Diagnostics are not adapters.
- Preserve earning integrity: never fabricate impressions, views, clicks, or credits.
- Do not create, retry, simulate, or mark payable any billing event from setup,
  install, repair, doctor, dashboard, generated commands, plugin tools, wrappers,
  or skills.
- Do not call billing, metrics, settlement, payout, Stripe money-movement, or
  event-ingest routes from diagnostics, dashboards, repairs, doctor, generated
  commands, plugin tools, or skills.
- Read local state first: `kickbacks api health`, `kickbacks sync status`, and `kickbacks doctor`; use `kickbacks app --no-open` only when a human specifically needs the dashboard.
- Use `kickbacks trust` for the two-way trust ledger: user risk, surface risk, eligibility states, payout holds, cap reasons, non-earning probe mode, and advertiser proof.
- Treat ledger freshness as visible and urgent without claiming Stripe failure from a stale account watermark alone.
- Treat installer and repair checks as non-earning probe mode; never make setup tests payable.
- Treat Stripe as backend-owned: the desktop app may show Connect status, requirements, and payout readiness, but must not hold Stripe secrets or create money movement.

## Useful Commands

- `kickbacks app` opens the dark desktop console.
- `kickbacks doctor` verifies local data, integrations, skills, and trust boundaries.
- `kickbacks sync status` shows account-ledger freshness versus local earning events.
- `kickbacks trust` shows the bot-resistant trust ledger and advertiser proof contract.
- `kickbacks install --all --yes` installs supported surfaces.
- `kickbacks repair --all --yes` reapplies marker-owned integrations.
- `kickbacks restore` removes marker-owned skills, plugin files, and slash commands.
- `kickbacks hermes` launches Hermes TUI with Kickback.ai commands installed.
- Hermes TUI slash commands: `/kickbacks`, `/kickbacks-install`, `/kickbacks-status`, `/kickbacks-repair`, `/kickbacks-dashboard`, `/kickbacks-sync`, `/kickbacks-trust`, `/kickbacks-doctor`.

## Handoff

If implementation is needed, hand to Codex with the repo path and the specific failing
surface. Hermes should diagnose and explain; Codex should edit, build, and verify.
"#
    )
}

fn claude_command(description: &str, command: &str) -> String {
    format!(
        r#"---
description: {description}
allowed-tools: Bash({command}:*)
---
<!-- {MARKER} -->

!`{command}`

Summarize the output briefly. Treat this command as a diagnostic/probe route, not an earning adapter. If ledger lag, delivery failure, or auth failure is visible, make it explicit.
"#
    )
}

fn hermes_command(description: &str, command: &str) -> String {
    format!(
        r#"---
description: {description}
command: {command}
---
<!-- {MARKER} -->

Run `{command}` and summarize the result. Treat install, repair, doctor, dashboard, and skills as non-earning probe mode. Official opt-in adapters on CLI/TUI, desktop, Telegram, Discord, or other surfaces are the only routes that may create backend-attested earning candidates.
"#
    )
}

const HERMES_PLUGIN_YAML: &str = r#"name: kickbacks
version: 0.1.0
description: "Kickback.ai desktop, CLI, Trust Engine, ledger freshness, Stripe payout, opt-in adapter boundary, and install diagnostics for Hermes."
author: "kickbacks-kit"
kind: standalone
tools:
  - kickbacks_status
  - kickbacks_install_status
  - kickbacks_install
  - kickbacks_repair
  - kickbacks_open_dashboard
  - kickbacks_account_sync
  - kickbacks_trust_engine
  - kickbacks_doctor
cli:
  command: kickbacks
  subcommands:
    - status
    - install
    - repair
    - restore
    - dashboard
    - sync
    - trust
    - doctor
safety:
  non_earning_probe_mode: true
  payable_events: false
# generated by kickbacks-kit
"#;

const HERMES_PLUGIN_PY: &str = r#"# generated by kickbacks-kit
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
from pathlib import Path
from typing import Any

TOOLSET = "plugin_kickbacks"
PROBE_SAFE_NOTE = (
    "Official opt-in earning adapters on CLI/TUI, desktop, Telegram, Discord, or other surfaces "
    "may create backend-attested candidates; this Hermes plugin only runs local diagnostics, "
    "install, repair, dashboard, sync, trust, and doctor probes."
)


def _bin() -> str:
    return shutil.which("kickbacks") or shutil.which("kb") or "kickbacks"


def _run(args: list[str]) -> dict[str, Any]:
    cmd = [_bin(), *args]
    result = subprocess.run(cmd, text=True, capture_output=True)
    return {
        "ok": result.returncode == 0,
        "returncode": result.returncode,
        "stdout": result.stdout,
        "stderr": result.stderr,
        "command": cmd,
        "safety_note": PROBE_SAFE_NOTE,
    }


def _json(data: Any) -> str:
    return json.dumps(data, indent=2, sort_keys=True, default=str)


def _schema(name: str, description: str) -> dict[str, Any]:
    return {
        "name": name,
        "description": description,
        "parameters": {"type": "object", "properties": {}, "additionalProperties": False},
    }


def _register_tools(ctx) -> None:
    ctx.register_tool(
        name="kickbacks_status",
        toolset=TOOLSET,
        description="Show Kickback.ai local status and ledger freshness monitor; probe-safe and non-earning.",
        emoji="status",
        schema=_schema("kickbacks_status", "Show Kickback.ai local status and ledger freshness monitor."),
        handler=lambda args, **_kw: _json(_run(["sync", "status", "--json"])),
    )
    ctx.register_tool(
        name="kickbacks_install_status",
        toolset=TOOLSET,
        description="Inspect Kickback.ai integration install state; probe-safe and non-earning.",
        emoji="plug",
        schema=_schema("kickbacks_install_status", "Inspect Kickback.ai integration install state."),
        handler=lambda args, **_kw: _json(_run(["api", "install/status"])),
    )
    ctx.register_tool(
        name="kickbacks_install",
        toolset=TOOLSET,
        description="Install marker-owned Kickback.ai Hermes files; probe-safe and non-earning.",
        emoji="plug",
        schema=_schema("kickbacks_install", "Install marker-owned Kickback.ai Hermes files."),
        handler=lambda args, **_kw: _json(_run(["install", "--hermes", "--skills", "--yes"])),
    )
    ctx.register_tool(
        name="kickbacks_repair",
        toolset=TOOLSET,
        description="Repair marker-owned Kickback.ai integrations; probe-safe and non-earning.",
        emoji="wrench",
        schema=_schema("kickbacks_repair", "Repair marker-owned Kickback.ai integrations."),
        handler=lambda args, **_kw: _json(_run(["repair", "--all", "--yes"])),
    )
    ctx.register_tool(
        name="kickbacks_open_dashboard",
        toolset=TOOLSET,
        description="Inspect Kickback.ai desktop dashboard API readiness without launching the long-running server.",
        emoji="dashboard",
        schema=_schema("kickbacks_open_dashboard", "Inspect the Kickback.ai desktop dashboard API readiness."),
        handler=lambda args, **_kw: _json(_run(["api", "health"])),
    )
    ctx.register_tool(
        name="kickbacks_account_sync",
        toolset=TOOLSET,
        description="Inspect account ledger freshness; probe-safe and non-earning.",
        emoji="sync",
        schema=_schema("kickbacks_account_sync", "Inspect account ledger freshness."),
        handler=lambda args, **_kw: _json(_run(["sync", "status", "--json"])),
    )
    ctx.register_tool(
        name="kickbacks_trust_engine",
        toolset=TOOLSET,
        description="Inspect Kickback.ai two-way trust ledger, bot-risk, payout holds, and advertiser proof; probe-safe and non-earning.",
        emoji="shield",
        schema=_schema("kickbacks_trust_engine", "Inspect Kickback.ai two-way trust ledger."),
        handler=lambda args, **_kw: _json(_run(["trust", "--json"])),
    )
    ctx.register_tool(
        name="kickbacks_doctor",
        toolset=TOOLSET,
        description="Run the non-earning Kickback.ai local doctor; never creates billing or payout events.",
        emoji="stethoscope",
        schema=_schema("kickbacks_doctor", "Run the non-earning Kickback.ai local doctor."),
        handler=lambda args, **_kw: _json(_run(["doctor"])),
    )


def _setup_cli(parser: argparse.ArgumentParser) -> None:
    sub = parser.add_subparsers(dest="command")
    for name in ["status", "install", "repair", "restore", "dashboard", "sync", "trust", "doctor"]:
        sub.add_parser(name)


def _handle_cli(args) -> None:
    command = args.command or "status"
    mapping = {
        "status": ["sync", "status"],
        "install": ["install", "--hermes", "--skills", "--yes"],
        "repair": ["repair", "--hermes", "--skills", "--yes"],
        "restore": ["restore"],
        "dashboard": ["api", "health"],
        "sync": ["sync", "status"],
        "trust": ["trust"],
        "doctor": ["doctor"],
    }
    print(_json(_run(mapping[command])))


def register(ctx) -> None:
    skill = Path.home() / ".hermes" / "skills" / "kickbacks" / "SKILL.md"
    if skill.exists():
        ctx.register_skill(
            name="kickbacks",
            path=skill,
            description="Kickback.ai Trust Engine, ledger freshness, desktop dashboard, Stripe payout, opt-in adapter boundary, and install diagnostics.",
        )
    _register_tools(ctx)
    ctx.register_cli_command(
        name="kickbacks",
        help="Inspect, install, and repair Kickback.ai from Hermes without creating earning events",
        setup_fn=_setup_cli,
        handler_fn=_handle_cli,
        description="Kickback.ai dashboard, Trust Engine, ledger freshness, opt-in adapter boundary, and probe-safe install diagnostics.",
    )
"#;

#[cfg(test)]
mod tests {
    use super::*;

    fn unique_temp_dir(name: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!(
            "kb-install-{name}-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn skill_contains_safety_and_sync_lag_rules() {
        let skill = skill_md("Codex");
        assert!(skill.contains("ledger freshness"));
        assert!(skill.contains("never fabricate"));
        assert!(skill.contains("non-earning probe mode"));
        assert!(skill.contains("kickbacks trust"));
        assert!(skill.contains("Stripe"));
        assert!(skill.contains("Official opt-in earning adapters"));
        assert!(skill.contains("Diagnostics are not adapters"));
        assert!(skill.contains("Do not create, retry, simulate, or mark payable"));
        assert!(skill.contains("kickbacks restore"));
        assert!(skill.contains("marker-owned"));
        assert!(skill.contains("/kickbacks-install"));
    }

    #[test]
    fn hermes_plugin_registers_expected_cli() {
        assert!(HERMES_PLUGIN_PY.contains("ctx.register_cli_command"));
        assert!(HERMES_PLUGIN_YAML.contains("tools:"));
        assert!(HERMES_PLUGIN_YAML.contains("kickbacks_install"));
        assert!(HERMES_PLUGIN_YAML.contains("non_earning_probe_mode: true"));
        assert!(HERMES_PLUGIN_PY.contains("PROBE_SAFE_NOTE"));
        assert!(HERMES_PLUGIN_PY.contains("kickbacks_account_sync"));
        assert!(HERMES_PLUGIN_PY.contains("kickbacks_install"));
        assert!(HERMES_PLUGIN_PY.contains("kickbacks_trust_engine"));
        assert!(HERMES_PLUGIN_PY.contains("kickbacks_doctor"));
        assert!(HERMES_PLUGIN_PY
            .contains("\"install\": [\"install\", \"--hermes\", \"--skills\", \"--yes\"]"));
        assert!(HERMES_PLUGIN_PY.contains("\"trust\": [\"trust\"]"));
        assert!(HERMES_PLUGIN_PY.contains("\"restore\": [\"restore\"]"));
        for command in [
            "status",
            "install",
            "repair",
            "dashboard",
            "sync",
            "trust",
            "doctor",
        ] {
            assert!(
                HERMES_PLUGIN_PY.contains(&format!("\"{command}\"")),
                "Hermes plugin missing command {command}"
            );
        }
        assert!(HERMES_PLUGIN_PY.contains("probe-safe and non-earning"));
        assert!(HERMES_PLUGIN_PY.contains("Telegram, Discord"));
    }

    #[test]
    fn generated_commands_are_probe_safe() {
        let claude = claude_command("Kickback.ai doctor", "kickbacks doctor");
        let hermes = hermes_command(
            "Kickback.ai install",
            "kickbacks install --hermes --skills --yes",
        );

        assert!(claude.contains("diagnostic/probe route"));
        assert!(hermes.contains("non-earning probe mode"));
        assert!(hermes.contains("Official opt-in adapters"));
    }

    #[test]
    fn write_marker_file_refuses_non_marker_overwrite() {
        let dir = unique_temp_dir("foreign-refusal");
        let path = dir.join("skill.md");
        let backup = dir.join("backups.jsonl");
        fs::write(&path, "user-owned content").unwrap();

        let err = write_marker_file_with_backup(
            &path,
            "<!-- generated by kickbacks-kit --> replacement",
            &backup,
        )
        .expect_err("foreign file must be refused");

        assert!(err.to_string().contains("refusing to overwrite"));
        assert_eq!(fs::read_to_string(&path).unwrap(), "user-owned content");
        assert!(!backup.exists());
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn idempotent_repair_does_not_duplicate_backup_records() {
        let dir = unique_temp_dir("idempotent");
        let path = dir.join("skill.md");
        let backup = dir.join("backups.jsonl");
        let original = "<!-- generated by kickbacks-kit --> old";
        let repaired = "<!-- generated by kickbacks-kit --> repaired";
        fs::write(&path, original).unwrap();

        write_marker_file_with_backup(&path, repaired, &backup).unwrap();
        write_marker_file_with_backup(&path, repaired, &backup).unwrap();

        let backups = fs::read_to_string(&backup).unwrap();
        assert_eq!(backups.lines().count(), 1);
        assert_eq!(fs::read_to_string(&path).unwrap(), repaired);
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn restore_uses_backup_record_byte_for_byte_when_available() {
        let dir = unique_temp_dir("restore-bytes");
        let path = dir.join("plugin.py");
        let backup = dir.join("backups.jsonl");
        let original = b"# generated by kickbacks-kit\r\nold bytes: \xff\r\n";
        let repaired = "# generated by kickbacks-kit\nnew bytes\n";
        fs::write(&path, original).unwrap();

        write_marker_file_with_backup(&path, repaired, &backup).unwrap();
        assert_eq!(fs::read_to_string(&path).unwrap(), repaired);

        let mut report = RestoreReport::default();
        restore_marker_file_with_backup(&path, &mut report, &backup).unwrap();

        assert_eq!(fs::read(&path).unwrap(), original);
        assert_eq!(report.restored, 1);
        assert_eq!(report.removed, 0);
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn restore_only_removes_marker_owned_files() {
        let dir = unique_temp_dir("restore");
        let owned = dir.join("owned.md");
        let foreign = dir.join("foreign.md");
        let missing = dir.join("missing.md");
        let backup = dir.join("backups.jsonl");
        fs::write(&owned, format!("<!-- {MARKER} -->")).unwrap();
        fs::write(&foreign, "user content").unwrap();

        let mut report = RestoreReport::default();
        restore_marker_file_with_backup(&owned, &mut report, &backup).unwrap();
        restore_marker_file_with_backup(&foreign, &mut report, &backup).unwrap();
        restore_marker_file_with_backup(&missing, &mut report, &backup).unwrap();

        assert!(!owned.exists());
        assert!(foreign.exists());
        assert_eq!(report.restored, 0);
        assert_eq!(report.removed, 1);
        assert_eq!(report.kept, 1);
        assert_eq!(report.missing, 1);
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn generated_probe_surfaces_do_not_include_billing_or_money_endpoints() {
        let surfaces = [
            ("skill", skill_md("Codex")),
            (
                "claude command",
                claude_command("Kickback.ai doctor", "kickbacks doctor"),
            ),
            (
                "hermes command",
                hermes_command("Kickback.ai trust", "kickbacks trust"),
            ),
            ("hermes plugin yaml", HERMES_PLUGIN_YAML.to_string()),
            ("hermes plugin py", HERMES_PLUGIN_PY.to_string()),
            ("doctor source", include_str!("doctor.rs").to_string()),
            (
                "integration source",
                include_str!("integrations.rs").to_string(),
            ),
        ];
        let forbidden = [
            "/v1/metrics",
            "/v1/events",
            "/v1/billing",
            "/v1/charges",
            "/v1/payment_intents",
            "/v1/payouts",
            "/v1/transfers",
            "/v1/refunds",
            "api.stripe.com",
            "metrics.kickbacks",
            "events.kickbacks",
            "billing.kickbacks",
            "fetch(\"/v1",
            "fetch('/v1",
            "Charge::create",
            "PaymentIntent::create",
            "Payout::create",
            "Transfer::create",
            "stripe::Client",
        ];
        for (surface, source) in surfaces {
            for pattern in forbidden {
                assert!(
                    !source.contains(pattern),
                    "{surface} contains forbidden endpoint or money-movement token {pattern}"
                );
            }
        }
    }
}
