use anyhow::{Context, Result};
use crossterm::style::Stylize;
use std::fs;
use std::path::Path;
use std::process::Command;

use crate::integrations;

const MARKER: &str = "generated by kickbacks-kit";

#[derive(Debug, Clone, Default)]
pub struct InstallSelection {
    pub all: bool,
    pub vscode: bool,
    pub claude_cli: bool,
    pub codex_cli: bool,
    pub hermes: bool,
    pub skills: bool,
    pub yes: bool,
}

pub fn install(selection: InstallSelection) -> Result<()> {
    let targets = selection.resolve();
    println!("{}", "kickbacks-kit - plug-and-play installer".bold());
    println!();

    if targets.vscode {
        install_vscode_extension()?;
    }
    if targets.claude_cli {
        crate::install_claude::install(selection.yes)?;
        install_claude_commands()?;
    }
    if targets.skills {
        install_skills()?;
    }
    if targets.hermes {
        install_hermes_plugin()?;
    }
    if targets.codex_cli {
        println!(
            "  {} Codex CLI integration ready through `kickbacks codex` and the Codex skill",
            "*".cyan()
        );
    }

    println!();
    println!(
        "{}",
        "Installed surfaces are visible in `kickbacks app`.".green()
    );
    Ok(())
}

pub fn repair(selection: InstallSelection) -> Result<()> {
    println!("{}", "kickbacks-kit - repair".bold());
    install(selection)
}

pub fn restore() -> Result<()> {
    println!("{}", "kickbacks-kit - restore".bold());
    println!();

    let home = dirs::home_dir().context("could not resolve home directory")?;
    let mut report = RestoreReport::default();

    for dir in [
        home.join(".claude").join("skills").join("kickbacks"),
        home.join(".codex").join("skills").join("kickbacks"),
        home.join(".hermes").join("skills").join("kickbacks"),
    ] {
        restore_marker_file(&dir.join("SKILL.md"), &mut report)?;
        remove_empty_dir(&dir)?;
    }

    let claude_commands = home.join(".claude").join("commands");
    for name in [
        "kbtop.md",
        "kbstatus.md",
        "kickbacks.md",
        "kickbacks-status.md",
        "kickbacks-repair.md",
        "kickbacks-dashboard.md",
        "kickbacks-trust.md",
        "kickbacks-doctor.md",
    ] {
        restore_marker_file(&claude_commands.join(name), &mut report)?;
    }

    let hermes_commands = home.join(".hermes").join("commands");
    for name in [
        "kickbacks.md",
        "kickbacks-status.md",
        "kickbacks-repair.md",
        "kickbacks-dashboard.md",
        "kickbacks-sync.md",
        "kickbacks-trust.md",
        "kickbacks-doctor.md",
    ] {
        restore_marker_file(&hermes_commands.join(name), &mut report)?;
    }

    let hermes_plugin = home.join(".hermes").join("plugins").join("kickbacks");
    for name in ["plugin.yaml", "__init__.py"] {
        restore_marker_file(&hermes_plugin.join(name), &mut report)?;
    }
    remove_empty_dir(&hermes_plugin)?;

    println!(
        "  {} restore summary: {} removed, {} kept, {} missing",
        "ok".green(),
        report.removed,
        report.kept,
        report.missing
    );
    println!(
        "  {} Use `kb uninstall-claude --yes` to restore Claude Code statusLine backup.",
        "*".yellow()
    );
    println!(
        "  {} Restore only removes marker-owned files.",
        "*".yellow()
    );
    Ok(())
}

impl InstallSelection {
    fn resolve(&self) -> Targets {
        let default_all = !self.all
            && !self.vscode
            && !self.claude_cli
            && !self.codex_cli
            && !self.hermes
            && !self.skills;
        Targets {
            vscode: default_all || self.all || self.vscode,
            claude_cli: default_all || self.all || self.claude_cli,
            codex_cli: default_all || self.all || self.codex_cli,
            hermes: default_all || self.all || self.hermes,
            skills: default_all
                || self.all
                || self.skills
                || self.claude_cli
                || self.codex_cli
                || self.hermes,
        }
    }
}

struct Targets {
    vscode: bool,
    claude_cli: bool,
    codex_cli: bool,
    hermes: bool,
    skills: bool,
}

fn install_vscode_extension() -> Result<()> {
    match integrations::find_executable("code") {
        Some(code) => {
            let status = Command::new(&code)
                .args(["--install-extension", "Kickbacksai.kickbacks-ai", "--force"])
                .status()
                .with_context(|| format!("running {}", code.display()))?;
            if status.success() {
                println!(
                    "  {} VS Code extension install/update requested",
                    "ok".green()
                );
            } else {
                println!(
                    "  {} VS Code extension command exited with {status}",
                    "*".yellow()
                );
            }
        }
        None => {
            println!(
                "  {} VS Code `code` command not found; install extension from Marketplace",
                "*".yellow()
            );
        }
    }
    Ok(())
}

fn install_skills() -> Result<()> {
    let home = dirs::home_dir().context("could not resolve home directory")?;
    let targets = [
        (
            home.join(".claude").join("skills").join("kickbacks"),
            skill_md("Claude"),
        ),
        (
            home.join(".codex").join("skills").join("kickbacks"),
            skill_md("Codex"),
        ),
        (
            home.join(".hermes").join("skills").join("kickbacks"),
            skill_md("Hermes"),
        ),
    ];
    for (dir, content) in targets {
        write_marker_file(&dir.join("SKILL.md"), &content)?;
        println!("  {} {}", "ok".green(), dir.join("SKILL.md").display());
    }
    Ok(())
}

fn install_claude_commands() -> Result<()> {
    let home = dirs::home_dir().context("could not resolve home directory")?;
    let commands = home.join(".claude").join("commands");
    let items = [
        (
            "kickbacks.md",
            claude_command("Kickbacks dashboard", "kickbacks app --no-open"),
        ),
        (
            "kickbacks-status.md",
            claude_command("Kickbacks status", "kickbacks sync status"),
        ),
        (
            "kickbacks-repair.md",
            claude_command(
                "Kickbacks repair",
                "kickbacks repair --claude-cli --skills --yes",
            ),
        ),
        (
            "kickbacks-dashboard.md",
            claude_command("Open Kickbacks dashboard", "kickbacks app"),
        ),
        (
            "kickbacks-trust.md",
            claude_command("Kickbacks Trust Engine", "kickbacks trust"),
        ),
        (
            "kickbacks-doctor.md",
            claude_command("Kickbacks doctor", "kickbacks doctor"),
        ),
    ];
    for (name, content) in items {
        write_marker_file(&commands.join(name), &content)?;
    }
    println!("  {} Claude slash commands installed", "ok".green());
    Ok(())
}

fn install_hermes_plugin() -> Result<()> {
    let home = dirs::home_dir().context("could not resolve home directory")?;
    let dir = home.join(".hermes").join("plugins").join("kickbacks");
    write_marker_file(&dir.join("plugin.yaml"), HERMES_PLUGIN_YAML)?;
    write_marker_file(&dir.join("__init__.py"), HERMES_PLUGIN_PY)?;
    install_hermes_tui_commands(&home)?;
    println!(
        "  {} Hermes plugin installed at {}",
        "ok".green(),
        dir.display()
    );
    Ok(())
}

fn install_hermes_tui_commands(home: &Path) -> Result<()> {
    let commands = home.join(".hermes").join("commands");
    let items = [
        (
            "kickbacks.md",
            hermes_command("Kickbacks trust status", "kickbacks trust"),
        ),
        (
            "kickbacks-status.md",
            hermes_command("Kickbacks sync status", "kickbacks sync status"),
        ),
        (
            "kickbacks-repair.md",
            hermes_command(
                "Kickbacks repair",
                "kickbacks repair --hermes --skills --yes",
            ),
        ),
        (
            "kickbacks-dashboard.md",
            hermes_command("Open Kickbacks dashboard", "kickbacks app"),
        ),
        (
            "kickbacks-sync.md",
            hermes_command("Kickbacks account sync", "kickbacks sync status"),
        ),
        (
            "kickbacks-trust.md",
            hermes_command("Kickbacks Trust Engine", "kickbacks trust"),
        ),
        (
            "kickbacks-doctor.md",
            hermes_command("Kickbacks doctor", "kickbacks doctor"),
        ),
    ];
    for (name, content) in items {
        write_marker_file(&commands.join(name), &content)?;
    }
    println!("  {} Hermes TUI command manifests installed", "ok".green());
    Ok(())
}

fn write_marker_file(path: &Path, content: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).with_context(|| format!("creating {}", parent.display()))?;
    }
    if path.exists() {
        let existing = fs::read_to_string(path).unwrap_or_default();
        if !existing.contains(MARKER) {
            anyhow::bail!(
                "{} exists and was not created by kickbacks-kit; refusing to overwrite",
                path.display()
            );
        }
    }
    fs::write(path, content).with_context(|| format!("writing {}", path.display()))?;
    Ok(())
}

#[derive(Default)]
struct RestoreReport {
    removed: usize,
    kept: usize,
    missing: usize,
}

fn restore_marker_file(path: &Path, report: &mut RestoreReport) -> Result<()> {
    if !path.exists() {
        report.missing += 1;
        return Ok(());
    }

    let existing = fs::read_to_string(path).unwrap_or_default();
    if existing.contains(MARKER) {
        fs::remove_file(path).with_context(|| format!("removing {}", path.display()))?;
        report.removed += 1;
        println!("  {} removed {}", "ok".green(), path.display());
    } else {
        report.kept += 1;
        println!("  {} kept non-marker file {}", "*".yellow(), path.display());
    }
    Ok(())
}

fn remove_empty_dir(path: &Path) -> Result<()> {
    if path.exists() {
        match fs::remove_dir(path) {
            Ok(()) => {}
            Err(err) if is_directory_not_empty(&err) => {}
            Err(err) if err.kind() == std::io::ErrorKind::NotFound => {}
            Err(err) => return Err(err).with_context(|| format!("removing {}", path.display())),
        }
    }
    Ok(())
}

fn is_directory_not_empty(err: &std::io::Error) -> bool {
    matches!(err.raw_os_error(), Some(145 | 39 | 17))
}

fn skill_md(surface: &str) -> String {
    format!(
        r#"---
name: kickbacks
description: "Kickbacks.ai desktop, CLI, ledger freshness, Stripe payout, and agent integration guidance. Use when working with Kickbacks.ai installs, earnings status, VS Code, Claude Code CLI, Codex CLI, Hermes Agent/TUI, Stripe payout readiness, or ledger diagnostics."
---

# Kickbacks.ai

<!-- {MARKER} -->

Use this skill when a user asks about Kickbacks.ai install state, earnings visibility,
ledger freshness, bot/fraud pressure, advertiser trust, Stripe payout readiness, or agent/CLI
setup from {surface}.

## Rules

- Preserve earning integrity: never fabricate impressions, views, clicks, or credits.
- Do not call billing or metrics routes from diagnostics, dashboards, repairs, or skills.
- Read local state first: `kickbacks sync status`, `kickbacks doctor`, and `kickbacks app`.
- Use `kickbacks trust` for the two-way trust ledger: user risk, surface risk, eligibility states, payout holds, cap reasons, non-earning probe mode, and advertiser proof.
- Treat ledger freshness as visible and urgent without claiming Stripe failure from a stale account watermark alone.
- Treat installer and repair checks as non-earning probe mode; never make setup tests payable.
- Treat Stripe as backend-owned: the desktop app may show Connect status, requirements, and payout readiness, but must not hold Stripe secrets or create money movement.

## Useful Commands

- `kickbacks app` opens the dark desktop console.
- `kickbacks doctor` verifies local data, integrations, skills, and trust boundaries.
- `kickbacks sync status` shows account-ledger freshness versus local earning events.
- `kickbacks trust` shows the bot-resistant trust ledger and advertiser proof contract.
- `kickbacks install --all --yes` installs supported surfaces.
- `kickbacks repair --all --yes` reapplies marker-owned integrations.
- `kickbacks restore` removes marker-owned skills, plugin files, and slash commands.
- `kickbacks hermes` launches Hermes TUI with Kickbacks installed.
- Hermes TUI slash commands: `/kickbacks`, `/kickbacks-status`, `/kickbacks-repair`, `/kickbacks-dashboard`, `/kickbacks-sync`, `/kickbacks-trust`, `/kickbacks-doctor`.

## Handoff

If implementation is needed, hand to Codex with the repo path and the specific failing
surface. Hermes should diagnose and explain; Codex should edit, build, and verify.
"#
    )
}

fn claude_command(description: &str, command: &str) -> String {
    format!(
        r#"---
description: {description}
allowed-tools: Bash({command}:*)
---
<!-- {MARKER} -->

!`{command}`

Summarize the output briefly. If ledger lag, delivery failure, or auth failure is visible, make it explicit.
"#
    )
}

fn hermes_command(description: &str, command: &str) -> String {
    format!(
        r#"---
description: {description}
command: {command}
---
<!-- {MARKER} -->

Run `{command}` and summarize the result. Treat install/repair as non-earning probe mode.
"#
    )
}

const HERMES_PLUGIN_YAML: &str = r#"name: kickbacks
version: 0.1.0
description: "Kickbacks.ai desktop, CLI, Trust Engine, ledger freshness, Stripe payout, and install diagnostics for Hermes."
author: "kickbacks-kit"
kind: standalone
# generated by kickbacks-kit
"#;

const HERMES_PLUGIN_PY: &str = r#"# generated by kickbacks-kit
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
from pathlib import Path
from typing import Any

TOOLSET = "plugin_kickbacks"


def _bin() -> str:
    return shutil.which("kickbacks") or shutil.which("kb") or "kickbacks"


def _run(args: list[str]) -> dict[str, Any]:
    cmd = [_bin(), *args]
    result = subprocess.run(cmd, text=True, capture_output=True)
    return {
        "ok": result.returncode == 0,
        "returncode": result.returncode,
        "stdout": result.stdout,
        "stderr": result.stderr,
        "command": cmd,
    }


def _json(data: Any) -> str:
    return json.dumps(data, indent=2, sort_keys=True, default=str)


def _schema(name: str, description: str) -> dict[str, Any]:
    return {
        "name": name,
        "description": description,
        "parameters": {"type": "object", "properties": {}, "additionalProperties": False},
    }


def _register_tools(ctx) -> None:
    ctx.register_tool(
        name="kickbacks_status",
        toolset=TOOLSET,
        description="Show Kickbacks local status and ledger freshness monitor.",
        emoji="status",
        schema=_schema("kickbacks_status", "Show Kickbacks local status and ledger freshness monitor."),
        handler=lambda args, **_kw: _json(_run(["sync", "status", "--json"])),
    )
    ctx.register_tool(
        name="kickbacks_install_status",
        toolset=TOOLSET,
        description="Inspect Kickbacks integration install state.",
        emoji="plug",
        schema=_schema("kickbacks_install_status", "Inspect Kickbacks integration install state."),
        handler=lambda args, **_kw: _json(_run(["api", "install/status"])),
    )
    ctx.register_tool(
        name="kickbacks_repair",
        toolset=TOOLSET,
        description="Repair marker-owned Kickbacks integrations.",
        emoji="wrench",
        schema=_schema("kickbacks_repair", "Repair marker-owned Kickbacks integrations."),
        handler=lambda args, **_kw: _json(_run(["repair", "--all", "--yes"])),
    )
    ctx.register_tool(
        name="kickbacks_open_dashboard",
        toolset=TOOLSET,
        description="Open the Kickbacks desktop dashboard.",
        emoji="dashboard",
        schema=_schema("kickbacks_open_dashboard", "Open the Kickbacks desktop dashboard."),
        handler=lambda args, **_kw: _json(_run(["app"])),
    )
    ctx.register_tool(
        name="kickbacks_account_sync",
        toolset=TOOLSET,
        description="Inspect account ledger freshness.",
        emoji="sync",
        schema=_schema("kickbacks_account_sync", "Inspect account ledger freshness."),
        handler=lambda args, **_kw: _json(_run(["sync", "status", "--json"])),
    )
    ctx.register_tool(
        name="kickbacks_trust_engine",
        toolset=TOOLSET,
        description="Inspect Kickbacks two-way trust ledger, bot-risk, payout holds, and advertiser proof.",
        emoji="shield",
        schema=_schema("kickbacks_trust_engine", "Inspect Kickbacks two-way trust ledger."),
        handler=lambda args, **_kw: _json(_run(["trust", "--json"])),
    )
    ctx.register_tool(
        name="kickbacks_doctor",
        toolset=TOOLSET,
        description="Run the non-earning Kickbacks local doctor.",
        emoji="stethoscope",
        schema=_schema("kickbacks_doctor", "Run the non-earning Kickbacks local doctor."),
        handler=lambda args, **_kw: _json(_run(["doctor"])),
    )


def _setup_cli(parser: argparse.ArgumentParser) -> None:
    sub = parser.add_subparsers(dest="command")
    for name in ["status", "install", "repair", "restore", "dashboard", "sync", "trust", "doctor"]:
        sub.add_parser(name)


def _handle_cli(args) -> None:
    command = args.command or "status"
    mapping = {
        "status": ["sync", "status"],
        "install": ["install", "--hermes", "--skills", "--yes"],
        "repair": ["repair", "--hermes", "--skills", "--yes"],
        "restore": ["restore"],
        "dashboard": ["app"],
        "sync": ["sync", "status"],
        "trust": ["trust"],
        "doctor": ["doctor"],
    }
    print(_json(_run(mapping[command])))


def register(ctx) -> None:
    skill = Path.home() / ".hermes" / "skills" / "kickbacks" / "SKILL.md"
    if skill.exists():
        ctx.register_skill(
            name="kickbacks",
            path=skill,
            description="Kickbacks.ai Trust Engine, ledger freshness, desktop dashboard, Stripe payout, and install diagnostics.",
        )
    _register_tools(ctx)
    ctx.register_cli_command(
        name="kickbacks",
        help="Inspect and repair Kickbacks.ai from Hermes",
        setup_fn=_setup_cli,
        handler_fn=_handle_cli,
        description="Kickbacks.ai dashboard, Trust Engine, ledger freshness, and install diagnostics.",
    )
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn skill_contains_safety_and_sync_lag_rules() {
        let skill = skill_md("Codex");
        assert!(skill.contains("ledger freshness"));
        assert!(skill.contains("never fabricate"));
        assert!(skill.contains("non-earning probe mode"));
        assert!(skill.contains("kickbacks trust"));
        assert!(skill.contains("Stripe"));
    }

    #[test]
    fn hermes_plugin_registers_expected_cli() {
        assert!(HERMES_PLUGIN_PY.contains("ctx.register_cli_command"));
        assert!(HERMES_PLUGIN_PY.contains("kickbacks_account_sync"));
        assert!(HERMES_PLUGIN_PY.contains("kickbacks_trust_engine"));
        assert!(HERMES_PLUGIN_PY.contains("kickbacks_doctor"));
        assert!(HERMES_PLUGIN_PY.contains("\"trust\": [\"trust\"]"));
        assert!(HERMES_PLUGIN_PY.contains("\"restore\": [\"restore\"]"));
    }

    #[test]
    fn restore_only_removes_marker_owned_files() {
        let dir = std::env::temp_dir().join(format!(
            "kb-install-restore-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        fs::create_dir_all(&dir).unwrap();
        let owned = dir.join("owned.md");
        let foreign = dir.join("foreign.md");
        let missing = dir.join("missing.md");
        fs::write(&owned, format!("<!-- {MARKER} -->")).unwrap();
        fs::write(&foreign, "user content").unwrap();

        let mut report = RestoreReport::default();
        restore_marker_file(&owned, &mut report).unwrap();
        restore_marker_file(&foreign, &mut report).unwrap();
        restore_marker_file(&missing, &mut report).unwrap();

        assert!(!owned.exists());
        assert!(foreign.exists());
        assert_eq!(report.removed, 1);
        assert_eq!(report.kept, 1);
        assert_eq!(report.missing, 1);
        fs::remove_dir_all(&dir).ok();
    }
}
