use anyhow::{Context, Result};
use serde::Serialize;
use std::cmp::Ordering;
use std::env;
use std::path::{Path, PathBuf};
use std::process::Command;

use crate::paths;

const MARKER: &str = "generated by kickbacks-kit";

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum IntegrationCapability {
    Earn,
    Observe,
    Configure,
}

#[derive(Debug, Clone, Serialize)]
pub struct IntegrationStatus {
    pub id: &'static str,
    pub label: &'static str,
    pub kind: &'static str,
    pub detected: bool,
    pub enabled: bool,
    pub capability: IntegrationCapability,
    pub version: Option<String>,
    pub path: Option<String>,
    pub detail: String,
    pub install_command: String,
    pub repair_command: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct SkillStatus {
    pub id: &'static str,
    pub label: &'static str,
    pub path: String,
    pub installed: bool,
    pub owned: bool,
    pub state: InstallState,
    pub detail: String,
    pub install_command: String,
    pub repair_command: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct StripeConnectStatus {
    pub backend_owned: bool,
    pub api_version: &'static str,
    pub account_api: &'static str,
    pub dashboard_access: &'static str,
    pub requirement_collection: &'static str,
    pub payouts_ready: Option<bool>,
    pub requirements_due: Vec<String>,
    pub note: &'static str,
}

#[derive(Debug, Clone, Serialize)]
pub struct SystemStatus {
    pub integrations: Vec<IntegrationStatus>,
    pub skills: Vec<SkillStatus>,
    pub stripe: StripeConnectStatus,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum InstallState {
    Missing,
    MarkerOwned,
    Foreign,
}

pub fn system_status() -> Result<SystemStatus> {
    Ok(SystemStatus {
        integrations: integrations()?,
        skills: skills()?,
        stripe: stripe_status(),
    })
}

pub fn integrations() -> Result<Vec<IntegrationStatus>> {
    Ok(vec![
        vscode_status(),
        claude_status(),
        codex_status(),
        hermes_status(),
    ])
}

pub fn skills() -> Result<Vec<SkillStatus>> {
    let home = dirs::home_dir().context("could not resolve home directory")?;
    Ok(skills_from_home(&home))
}

fn skills_from_home(home: &Path) -> Vec<SkillStatus> {
    let entries = [
        (
            "claude",
            "Claude skill",
            home.join(".claude")
                .join("skills")
                .join("kickbacks")
                .join("SKILL.md"),
        ),
        (
            "codex",
            "Codex skill",
            home.join(".codex")
                .join("skills")
                .join("kickbacks")
                .join("SKILL.md"),
        ),
        (
            "hermes",
            "Hermes skill",
            home.join(".hermes")
                .join("skills")
                .join("kickbacks")
                .join("SKILL.md"),
        ),
    ];
    entries
        .into_iter()
        .map(|(id, label, path)| SkillStatus {
            id,
            label,
            installed: path.exists(),
            owned: install_state(&path) == InstallState::MarkerOwned,
            state: install_state(&path),
            detail: install_state_detail(&path, "skill"),
            path: path.display().to_string(),
            install_command: match id {
                "claude" => "kickbacks install --claude-cli --skills".to_string(),
                "codex" => "kickbacks install --codex-cli --skills".to_string(),
                "hermes" => "kickbacks install --hermes --skills".to_string(),
                _ => "kickbacks install --skills".to_string(),
            },
            repair_command: match id {
                "claude" => "kickbacks repair --claude-cli --skills --yes".to_string(),
                "codex" => "kickbacks repair --codex-cli --skills --yes".to_string(),
                "hermes" => "kickbacks repair --hermes --skills --yes".to_string(),
                _ => "kickbacks repair --skills --yes".to_string(),
            },
        })
        .collect()
}

pub fn stripe_status() -> StripeConnectStatus {
    StripeConnectStatus {
        backend_owned: true,
        api_version: "2026-05-27.dahlia",
        account_api: "Stripe Connect Accounts v2 (/v2/core/accounts)",
        dashboard_access: "Express-style dashboard access via controller properties",
        requirement_collection: "Stripe/Kickback.ai backend collects requirements; local diagnostics are display-only",
        payouts_ready: None,
        requirements_due: Vec::new(),
        note: "Desktop app must not hold Stripe secret keys or create money movement. It displays backend-provided Connect account, requirements, and payout readiness.",
    }
}

pub fn run_wrapped(tool: &str, default_args: &[&str], args: &[String]) -> Result<()> {
    let mut final_args: Vec<String> = if args.is_empty() {
        default_args.iter().map(|s| (*s).to_string()).collect()
    } else {
        args.to_vec()
    };
    if final_args.first().map(String::as_str) == Some("--") {
        final_args.remove(0);
    }
    let exe = find_executable(tool).with_context(|| format!("{tool} was not found on PATH"))?;
    let status = Command::new(&exe)
        .args(&final_args)
        .status()
        .with_context(|| format!("launching {}", exe.display()))?;
    if !status.success() {
        anyhow::bail!("{tool} exited with status {status}");
    }
    Ok(())
}

pub fn installed_extension_dir() -> Option<PathBuf> {
    let home = dirs::home_dir()?;
    installed_extension_dir_from(&home.join(".vscode").join("extensions"))
}

pub fn find_executable(name: &str) -> Option<PathBuf> {
    let name_path = Path::new(name);
    if name_path.is_absolute() && name_path.exists() {
        return Some(name_path.to_path_buf());
    }
    let path = env::var_os("PATH")?;
    let exts = executable_extensions();
    for dir in env::split_paths(&path) {
        let direct = dir.join(name);
        if direct.is_file() {
            return Some(direct);
        }
        for ext in &exts {
            let candidate = dir.join(format!("{name}{ext}"));
            if candidate.is_file() {
                return Some(candidate);
            }
        }
    }
    None
}

fn executable_extensions() -> Vec<String> {
    if cfg!(windows) {
        env::var("PATHEXT")
            .unwrap_or_else(|_| ".COM;.EXE;.BAT;.CMD".to_string())
            .split(';')
            .map(|s| s.to_ascii_lowercase())
            .collect()
    } else {
        vec![String::new()]
    }
}

fn earning_adapter_capability(enabled: bool) -> IntegrationCapability {
    if enabled {
        IntegrationCapability::Earn
    } else {
        IntegrationCapability::Configure
    }
}

fn probe_surface_capability(enabled: bool) -> IntegrationCapability {
    if enabled {
        IntegrationCapability::Observe
    } else {
        IntegrationCapability::Configure
    }
}

fn vscode_status() -> IntegrationStatus {
    vscode_status_from(find_executable("code"), installed_extension_dir())
}

fn vscode_status_from(code: Option<PathBuf>, extension: Option<PathBuf>) -> IntegrationStatus {
    let has_extension = extension.is_some();
    let version = extension.as_ref().and_then(|p| extension_version(p));
    IntegrationStatus {
        id: "vscode",
        label: "VS Code extension",
        kind: "desktop_editor",
        detected: code.is_some() || has_extension,
        enabled: has_extension,
        capability: earning_adapter_capability(has_extension),
        version,
        path: extension.or(code).map(|p| p.display().to_string()),
        detail: if has_extension {
            "Kickback.ai VS Code adapter detected; earning candidates still require opt-in, visible wait-state proof, backend attestation, caps, refund windows, and reconciliation".to_string()
        } else {
            "Install an official Kickback.ai adapter to enable opt-in earning on a supported surface; diagnostics remain probe-only".to_string()
        },
        install_command: "kickbacks install --vscode".to_string(),
        repair_command: "kickbacks repair --vscode".to_string(),
    }
}

fn claude_status() -> IntegrationStatus {
    let exe = find_executable("claude");
    let home = dirs::home_dir();
    claude_status_from(home.as_deref(), exe, tool_version("claude"))
}

fn claude_status_from(
    home: Option<&Path>,
    exe: Option<PathBuf>,
    version: Option<String>,
) -> IntegrationStatus {
    let settings = home.map(|h| h.join(".claude").join("settings.json"));
    let statusline_enabled = settings
        .as_ref()
        .and_then(|p| std::fs::read_to_string(p).ok())
        .map(|s| claude_statusline_enabled(&s))
        .unwrap_or(false);
    let command_paths = home.map(claude_command_paths).unwrap_or_default();
    let commands_owned = all_marker_owned(&command_paths);
    let skill = home.map(|h| {
        h.join(".claude")
            .join("skills")
            .join("kickbacks")
            .join("SKILL.md")
    });
    let skill_owned = skill
        .as_ref()
        .map(|p| install_state(p) == InstallState::MarkerOwned)
        .unwrap_or(false);
    let enabled = exe.is_some() && statusline_enabled && commands_owned && skill_owned;
    let detected = exe.is_some()
        || settings.as_ref().map(|p| p.exists()).unwrap_or(false)
        || command_paths.iter().any(|p| p.exists())
        || skill.as_ref().map(|p| p.exists()).unwrap_or(false);
    IntegrationStatus {
        id: "claude",
        label: "Claude Code CLI",
        kind: "cli",
        detected,
        enabled,
        capability: probe_surface_capability(enabled),
        version,
        path: exe.map(|p| p.display().to_string()),
        detail: if enabled {
            "Claude statusLine, slash commands, and skill are marker-owned probe/control surfaces; earning remains owned by official opt-in adapters".to_string()
        } else if statusline_enabled {
            "Claude statusLine is wired; run repair to add marker-owned commands and skill without creating payable events"
                .to_string()
        } else if detected {
            "Claude found; run the installer to add probe-safe statusLine, slash commands, and skill"
                .to_string()
        } else {
            "Run the installer to add probe-safe statusLine, slash commands, and skill".to_string()
        },
        install_command: "kickbacks install --claude-cli --skills".to_string(),
        repair_command: "kickbacks repair --claude-cli --skills --yes".to_string(),
    }
}

fn codex_status() -> IntegrationStatus {
    let exe = find_executable("codex");
    let home = dirs::home_dir();
    codex_status_from(home.as_deref(), exe, tool_version("codex"))
}

fn codex_status_from(
    home: Option<&Path>,
    exe: Option<PathBuf>,
    version: Option<String>,
) -> IntegrationStatus {
    let skill = home.map(|h| {
        h.join(".codex")
            .join("skills")
            .join("kickbacks")
            .join("SKILL.md")
    });
    let skill_state = skill.as_ref().map(|p| install_state(p));
    let enabled = exe.is_some() && skill_state == Some(InstallState::MarkerOwned);
    IntegrationStatus {
        id: "codex",
        label: "Codex CLI",
        kind: "cli",
        detected: exe.is_some() || skill.as_ref().map(|p| p.exists()).unwrap_or(false),
        enabled,
        capability: probe_surface_capability(enabled),
        version,
        path: exe.map(|p| p.display().to_string()),
        detail: match skill_state {
            Some(InstallState::MarkerOwned) => {
                "Codex wrapper and marker-owned skill support probe-safe Kickback.ai diagnostics; earning candidates remain owned by official opt-in adapters".to_string()
            }
            Some(InstallState::Foreign) => {
                "Codex skill exists but is not installer-owned; repair will refuse to overwrite it".to_string()
            }
            _ => {
                "Install the Codex skill; wrapper diagnostics remain non-earning probe mode".to_string()
            }
        },
        install_command: "kickbacks install --codex-cli --skills".to_string(),
        repair_command: "kickbacks repair --codex-cli --skills --yes".to_string(),
    }
}

fn hermes_status() -> IntegrationStatus {
    let exe = find_executable("hermes");
    let home = dirs::home_dir();
    hermes_status_from(home.as_deref(), exe, tool_version("hermes"))
}

fn hermes_status_from(
    home: Option<&Path>,
    exe: Option<PathBuf>,
    version: Option<String>,
) -> IntegrationStatus {
    let plugin_paths = home.map(hermes_plugin_paths).unwrap_or_default();
    let skill = home.map(|h| {
        h.join(".hermes")
            .join("skills")
            .join("kickbacks")
            .join("SKILL.md")
    });
    let command_paths = home.map(hermes_command_paths).unwrap_or_default();
    let plugin_owned = all_marker_owned(&plugin_paths);
    let skill_owned = skill
        .as_ref()
        .map(|p| install_state(p) == InstallState::MarkerOwned)
        .unwrap_or(false);
    let commands_owned = all_marker_owned(&command_paths);
    let enabled = exe.is_some() && plugin_owned && skill_owned && commands_owned;
    IntegrationStatus {
        id: "hermes",
        label: "Hermes Agent/TUI",
        kind: "agent_tui",
        detected: exe.is_some()
            || plugin_paths.iter().any(|p| p.exists())
            || skill.as_ref().map(|p| p.exists()).unwrap_or(false)
            || command_paths.iter().any(|p| p.exists()),
        enabled,
        capability: probe_surface_capability(enabled),
        version,
        path: plugin_paths
            .first()
            .cloned()
            .or(exe)
            .map(|p| p.display().to_string()),
        detail: if enabled {
            "Hermes plugin, skill, CLI group, and TUI commands are marker-owned probe/control surfaces".to_string()
        } else if plugin_owned || skill_owned || commands_owned {
            "Hermes integration is partially installed; run repair to refresh marker-owned files without creating payable events"
                .to_string()
        } else {
            "Install the Hermes probe-safe plugin, skill, TUI slash commands, and CLI group"
                .to_string()
        },
        install_command: "kickbacks install --hermes --skills".to_string(),
        repair_command: "kickbacks repair --hermes --skills --yes".to_string(),
    }
}

fn tool_version(tool: &str) -> Option<String> {
    let exe = find_executable(tool)?;
    let output = Command::new(exe).arg("--version").output().ok()?;
    if !output.status.success() {
        return None;
    }
    let bytes = if output.stdout.is_empty() {
        &output.stderr
    } else {
        &output.stdout
    };
    let raw = String::from_utf8_lossy(bytes);
    Some(raw.lines().next().unwrap_or_default().trim().to_string())
}

pub fn auth_status() -> Result<String> {
    let auth = dirs::home_dir()
        .context("could not resolve home directory")?
        .join(".kickbacks")
        .join("auth.json");
    if !auth.exists() {
        return Ok("not signed in (no ~/.kickbacks/auth.json)".to_string());
    }
    let raw = std::fs::read_to_string(&auth)?;
    let v: serde_json::Value = serde_json::from_str(&raw).unwrap_or_default();
    let has_client = v.get("clientId").and_then(|x| x.as_str()).is_some();
    let has_refresh = v.get("refresh").and_then(|x| x.as_str()).is_some();
    Ok(format!(
        "auth file present; client id {}; refresh token {}",
        if has_client { "present" } else { "missing" },
        if has_refresh { "present" } else { "missing" }
    ))
}

pub fn app_data_paths() -> Result<Vec<(String, String)>> {
    Ok(vec![
        (
            "archive_db".to_string(),
            paths::db_path()?.display().to_string(),
        ),
        (
            "vibe_dir".to_string(),
            paths::vibe_dir()?.display().to_string(),
        ),
        (
            "debug_log".to_string(),
            paths::debug_log_path()?.display().to_string(),
        ),
    ])
}

fn install_state(path: &Path) -> InstallState {
    if !path.exists() {
        return InstallState::Missing;
    }
    match std::fs::read_to_string(path) {
        Ok(content) if content.contains(MARKER) => InstallState::MarkerOwned,
        _ => InstallState::Foreign,
    }
}

fn install_state_detail(path: &Path, noun: &str) -> String {
    match install_state(path) {
        InstallState::Missing => format!("{noun} not installed"),
        InstallState::MarkerOwned => format!("{noun} installed by kickbacks-kit"),
        InstallState::Foreign => {
            format!("{noun} exists but is not marker-owned; repair will not overwrite it")
        }
    }
}

fn all_marker_owned(paths: &[PathBuf]) -> bool {
    !paths.is_empty()
        && paths
            .iter()
            .all(|path| install_state(path) == InstallState::MarkerOwned)
}

fn claude_command_paths(home: &Path) -> Vec<PathBuf> {
    let dir = home.join(".claude").join("commands");
    [
        "kickbacks.md",
        "kickbacks-status.md",
        "kickbacks-repair.md",
        "kickbacks-dashboard.md",
        "kickbacks-trust.md",
        "kickbacks-doctor.md",
    ]
    .into_iter()
    .map(|name| dir.join(name))
    .collect()
}

fn hermes_command_paths(home: &Path) -> Vec<PathBuf> {
    let dir = home.join(".hermes").join("commands");
    [
        "kickbacks.md",
        "kickbacks-install.md",
        "kickbacks-status.md",
        "kickbacks-repair.md",
        "kickbacks-dashboard.md",
        "kickbacks-sync.md",
        "kickbacks-trust.md",
        "kickbacks-doctor.md",
    ]
    .into_iter()
    .map(|name| dir.join(name))
    .collect()
}

fn hermes_plugin_paths(home: &Path) -> Vec<PathBuf> {
    let dir = home.join(".hermes").join("plugins").join("kickbacks");
    ["plugin.yaml", "__init__.py"]
        .into_iter()
        .map(|name| dir.join(name))
        .collect()
}

fn claude_statusline_enabled(raw_settings: &str) -> bool {
    let parsed = serde_json::from_str::<serde_json::Value>(raw_settings)
        .ok()
        .and_then(|v| {
            v.get("statusLine")
                .and_then(|s| s.get("command"))
                .and_then(|c| c.as_str())
                .map(str::to_string)
        });
    parsed
        .as_deref()
        .map(command_is_kickbacks_statusline)
        .unwrap_or_else(|| {
            raw_settings.contains("kb statusline") || raw_settings.contains("kickbacks statusline")
        })
}

fn command_is_kickbacks_statusline(command: &str) -> bool {
    command.contains("kb statusline")
        || command.contains("kickbacks statusline")
        || (command.contains("kb.exe") && command.contains("statusline"))
        || (command.contains("kickbacks.exe") && command.contains("statusline"))
}

fn installed_extension_dir_from(exts_dir: &Path) -> Option<PathBuf> {
    let entries = std::fs::read_dir(exts_dir).ok()?;
    entries
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| extension_version(p).is_some())
        .max_by(|a, b| compare_extension_paths(a, b))
}

fn compare_extension_paths(a: &Path, b: &Path) -> Ordering {
    match (extension_version(a), extension_version(b)) {
        (Some(left), Some(right)) => compare_versions(&left, &right),
        (Some(_), None) => Ordering::Greater,
        (None, Some(_)) => Ordering::Less,
        (None, None) => Ordering::Equal,
    }
}

fn extension_version(path: &Path) -> Option<String> {
    let name = path.file_name().and_then(|n| n.to_str())?;
    let prefix = "kickbacksai.kickbacks-ai-";
    if name.len() <= prefix.len() || !name[..prefix.len()].eq_ignore_ascii_case(prefix) {
        return None;
    }
    Some(name[prefix.len()..].to_string())
}

fn compare_versions(a: &str, b: &str) -> Ordering {
    let a_parts = version_parts(a);
    let b_parts = version_parts(b);
    for i in 0..a_parts.len().max(b_parts.len()) {
        let left = *a_parts.get(i).unwrap_or(&0);
        let right = *b_parts.get(i).unwrap_or(&0);
        match left.cmp(&right) {
            Ordering::Equal => {}
            ord => return ord,
        }
    }
    a.cmp(b)
}

fn version_parts(version: &str) -> Vec<u64> {
    version
        .split(|c: char| !c.is_ascii_digit())
        .filter(|part| !part.is_empty())
        .filter_map(|part| part.parse::<u64>().ok())
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::time::{SystemTime, UNIX_EPOCH};

    struct TempDir(PathBuf);

    impl TempDir {
        fn new(name: &str) -> Self {
            let stamp = SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .unwrap()
                .as_nanos();
            let dir = env::temp_dir().join(format!(
                "kb-integrations-{name}-{}-{stamp}",
                std::process::id()
            ));
            fs::create_dir_all(&dir).unwrap();
            Self(dir)
        }

        fn path(&self) -> &Path {
            &self.0
        }
    }

    impl Drop for TempDir {
        fn drop(&mut self) {
            fs::remove_dir_all(&self.0).ok();
        }
    }

    #[test]
    fn install_state_requires_marker() {
        let dir = TempDir::new("marker");
        let missing = dir.path().join("missing.md");
        assert_eq!(install_state(&missing), InstallState::Missing);

        let foreign = dir.path().join("foreign.md");
        fs::write(&foreign, "name: kickbacks").unwrap();
        assert_eq!(install_state(&foreign), InstallState::Foreign);

        let owned = dir.path().join("owned.md");
        fs::write(&owned, format!("<!-- {MARKER} -->")).unwrap();
        assert_eq!(install_state(&owned), InstallState::MarkerOwned);
    }

    #[test]
    fn extension_detection_uses_numeric_version_order() {
        let dir = TempDir::new("extensions");
        fs::create_dir_all(dir.path().join("kickbacksai.kickbacks-ai-0.3.99")).unwrap();
        fs::create_dir_all(dir.path().join("kickbacksai.kickbacks-ai-0.3.174")).unwrap();
        fs::create_dir_all(dir.path().join("Kickbacksai.Kickbacks-AI-0.3.200")).unwrap();
        fs::create_dir_all(dir.path().join("unrelated.extension-9.9.9")).unwrap();

        let found = installed_extension_dir_from(dir.path()).unwrap();
        assert_eq!(extension_version(&found).as_deref(), Some("0.3.200"));
    }

    #[test]
    fn claude_statusline_detection_parses_json_and_exe_paths() {
        assert!(claude_statusline_enabled(
            r#"{"statusLine":{"command":"\"C:\\tools\\kickbacks.exe\" statusline"}}"#
        ));
        assert!(claude_statusline_enabled("kb statusline"));
        assert!(!claude_statusline_enabled(
            r#"{"statusLine":{"command":"custom-status.sh"}}"#
        ));
    }

    #[test]
    fn skill_detection_reports_marker_foreign_and_missing_states() {
        let dir = TempDir::new("skills");
        let claude = dir
            .path()
            .join(".claude")
            .join("skills")
            .join("kickbacks")
            .join("SKILL.md");
        let codex = dir
            .path()
            .join(".codex")
            .join("skills")
            .join("kickbacks")
            .join("SKILL.md");
        fs::create_dir_all(claude.parent().unwrap()).unwrap();
        fs::create_dir_all(codex.parent().unwrap()).unwrap();
        fs::write(&claude, format!("<!-- {MARKER} -->")).unwrap();
        fs::write(&codex, "user-owned skill").unwrap();

        let skills = skills_from_home(dir.path());
        let claude = skills.iter().find(|s| s.id == "claude").unwrap();
        let codex = skills.iter().find(|s| s.id == "codex").unwrap();
        let hermes = skills.iter().find(|s| s.id == "hermes").unwrap();

        assert_eq!(claude.state, InstallState::MarkerOwned);
        assert!(claude.owned);
        assert_eq!(codex.state, InstallState::Foreign);
        assert!(!codex.owned);
        assert!(codex.detail.contains("repair will not overwrite"));
        assert_eq!(hermes.state, InstallState::Missing);
    }

    #[test]
    fn probe_surfaces_are_observe_not_earning_capability() {
        assert_eq!(
            earning_adapter_capability(true),
            IntegrationCapability::Earn
        );
        assert_eq!(
            earning_adapter_capability(false),
            IntegrationCapability::Configure
        );
        assert_eq!(
            probe_surface_capability(true),
            IntegrationCapability::Observe
        );
        assert_eq!(
            probe_surface_capability(false),
            IntegrationCapability::Configure
        );
    }

    #[test]
    fn claude_detection_requires_cli_and_marker_owned_surfaces() {
        let dir = TempDir::new("claude");
        let settings = dir.path().join(".claude").join("settings.json");
        fs::create_dir_all(settings.parent().unwrap()).unwrap();
        fs::write(&settings, r#"{"statusLine":{"command":"kb statusline"}}"#).unwrap();
        for path in claude_command_paths(dir.path()) {
            fs::create_dir_all(path.parent().unwrap()).unwrap();
            fs::write(path, format!("<!-- {MARKER} -->")).unwrap();
        }
        let skill = dir
            .path()
            .join(".claude")
            .join("skills")
            .join("kickbacks")
            .join("SKILL.md");
        fs::create_dir_all(skill.parent().unwrap()).unwrap();
        fs::write(&skill, format!("<!-- {MARKER} -->")).unwrap();

        let without_cli = claude_status_from(Some(dir.path()), None, None);
        let with_cli = claude_status_from(
            Some(dir.path()),
            Some(dir.path().join("claude.exe")),
            Some("Claude 2.0".to_string()),
        );

        assert!(without_cli.detected);
        assert!(!without_cli.enabled);
        assert_eq!(without_cli.capability, IntegrationCapability::Configure);
        assert!(with_cli.enabled);
        assert_eq!(with_cli.capability, IntegrationCapability::Observe);
        assert!(with_cli.detail.contains("probe/control"));
    }

    #[test]
    fn codex_detection_requires_cli_for_enabled_state() {
        let dir = TempDir::new("codex");
        let skill = dir
            .path()
            .join(".codex")
            .join("skills")
            .join("kickbacks")
            .join("SKILL.md");
        fs::create_dir_all(skill.parent().unwrap()).unwrap();
        fs::write(&skill, format!("<!-- {MARKER} -->")).unwrap();

        let without_cli = codex_status_from(Some(dir.path()), None, None);
        let with_cli = codex_status_from(
            Some(dir.path()),
            Some(dir.path().join("codex.exe")),
            Some("codex 1.0".to_string()),
        );

        assert!(without_cli.detected);
        assert!(!without_cli.enabled);
        assert_eq!(without_cli.capability, IntegrationCapability::Configure);
        assert!(with_cli.enabled);
        assert_eq!(with_cli.capability, IntegrationCapability::Observe);
    }

    #[test]
    fn hermes_detection_requires_plugin_skill_commands_and_cli() {
        let dir = TempDir::new("hermes");
        for path in hermes_plugin_paths(dir.path())
            .into_iter()
            .chain(hermes_command_paths(dir.path()))
        {
            fs::create_dir_all(path.parent().unwrap()).unwrap();
            fs::write(path, format!("<!-- {MARKER} -->")).unwrap();
        }
        let skill = dir
            .path()
            .join(".hermes")
            .join("skills")
            .join("kickbacks")
            .join("SKILL.md");
        fs::create_dir_all(skill.parent().unwrap()).unwrap();
        fs::write(&skill, format!("<!-- {MARKER} -->")).unwrap();

        let without_cli = hermes_status_from(Some(dir.path()), None, None);
        let with_cli = hermes_status_from(
            Some(dir.path()),
            Some(dir.path().join("hermes.exe")),
            Some("hermes 1.0".to_string()),
        );

        assert!(without_cli.detected);
        assert!(!without_cli.enabled);
        assert_eq!(without_cli.capability, IntegrationCapability::Configure);
        assert!(with_cli.enabled);
        assert_eq!(with_cli.capability, IntegrationCapability::Observe);
        assert!(with_cli.detail.contains("probe/control"));
    }

    #[test]
    fn hermes_plugin_detection_requires_manifest_and_python_registration() {
        let dir = TempDir::new("hermes-partial");
        let plugin_yaml = dir
            .path()
            .join(".hermes")
            .join("plugins")
            .join("kickbacks")
            .join("plugin.yaml");
        fs::create_dir_all(plugin_yaml.parent().unwrap()).unwrap();
        fs::write(&plugin_yaml, format!("<!-- {MARKER} -->")).unwrap();

        let status = hermes_status_from(
            Some(dir.path()),
            Some(dir.path().join("hermes.exe")),
            Some("hermes 1.0".to_string()),
        );

        assert!(status.detected);
        assert!(!status.enabled);
        assert!(status.detail.contains("Install the Hermes probe-safe"));
    }
}
